config {
    type: "incremental",
    schema: "mart",
    tags: ["fact", "gold"],
    uniqueKey: ["id_venta"],
    dependencies: ["stg_ventas", "stg_clientes", "dim_productos"]
}

js {
    const {
        procDate
    } = require("includes/helpers");
}

SELECT
  v.venta_id,
  v.fecha_venta,
  v.producto_id,
  v.cliente_id,
  v.cantidad,
  v.precio_unitario,
  v.monto,
  c.region,
  p.categoria
FROM
  ${ref("stg_ventas")} v
LEFT JOIN
  ${ref("stg_clientes")} c
USING
  (id_cliente)
LEFT JOIN
  ${ref("dim_productos")} p
USING
  (id_producto)
${ when(incremental(), `WHERE v.fecha_venta = ${procDate()}`) }
